### ISSUE TITLE
Adding GCP content from Cloud Community Days and Cloud NEXT

### ISSUE THREAD

**Issue by sayakpaul** [rominirani/googlecloud-indiacommunity-presentations#1]
### CCD Kolkata

* CCD Date: August 28, 2022
* CCD City: Kolkata
* Your Name: Sayak Paul
* Your talk topic: Improving Dataflow pipelines for text data at scale
* Deck link: https://docs.google.com/presentation/d/1EAn4_pNZzt0_8mz_VAuccSySU3DpNoYN5X04amvkbC0/edit?usp=sharing

### CCD Ahmedabad

* CCD Date: September 24, 2022
* CCD City: Ahmedabad
* Your Name: Sayak Paul
* Your talk topic: Fantastic ML Deployments & How to do them with Vertex AI
* Deck link: https://bit.ly/ccd-ahm-deck
* Code repository: https://github.com/sayakpaul/ccd-ahm-2022

## Cloud NEXT

* Date: October 13, 2022
* City: Bangalore
* Your Name: Sayak Paul
* Your talk topic: Better Hardware Provisioning for ML Experiments on GCP
* Deck link: https://github.com/carted/cloud-next-22-terraform/blob/main/slides/Cloud%20Next%202022%20-%20Sayak.pdf
* Code repository: https://github.com/carted/cloud-next-22-terraform

**Comment by sayakpaul** [comment]
@rominirani since I am not a collaborator of this repository, I don't have the permissions to add labels.

**Comment by rominirani** [comment]
Thanks @sayakpaul . I have removed the instructions part where the label is mentioned.
