### ISSUE TITLE
Adding content for GCP (Vertex AI) from DevFest Raipur and DevFest Mumbai

### ISSUE THREAD

**Issue by suvadityamuk** [rominirani/googlecloud-indiacommunity-presentations#10]
# GDG DevFest 2022

## DevFest Raipur
- Date: 17/12/2022 (Saturday)
- Name: Suvaditya Mukherjee
- City: Raipur, Chattisgarh
- Topic: Accelerating Model Deployment using Transfer Learning and Vertex AI
- Blog link: https://medium.com/google-cloud/accelerating-model-deployment-using-transfer-learning-and-vertex-ai-6ee6cc7332e9
- Repo link: https://github.com/suvadityamuk/Devfest-Raipur-22
- Slide deck link: https://bit.ly/tf-vertex-ai

## DevFest Mumbai
- Date: 05/12/2022 (Monday)
- Name: Suvaditya Mukherjee
- City: Mumbai, Maharashtra
- Topic: Preparing your ML Models for the Cloud
- Slide deck link: https://bit.ly/cloud-ml-22

**Comment by rominirani** [comment]
Thank you.
