### ISSUE TITLE
Serverless on Google Cloud

### ISSUE THREAD

**Issue by kartikderasari** [rominirani/googlecloud-indiacommunity-presentations#11]
- Date: 6th November 2022
- Event: DevFest
- City: Udaipur
- Your Name: Kartik Derasari
- Your talk topic: Serverless on Google Cloud
- Presentation link: https://docs.google.com/presentation/d/13_kLqUCzaYIBz7EY8-m1mdHuWi5Tbyaris8Jxr5k1A8/edit?usp=sharing

**Comment by rominirani** [comment]
Thank you
