### ISSUE TITLE
Scaling your Web-Apps using Firebase & Google Cloud

### ISSUE THREAD

**Issue by kartikderasari** [rominirani/googlecloud-indiacommunity-presentations#12]
- Date: 25th June, 2022
- Event: Google IO Extended
- City: Ahmedabad
- Your Name: Kartik Derasari
- Your talk topic: Scaling your Web-Apps using Firebase & Google Cloud
- Presentation link: https://docs.google.com/presentation/d/1f6wsimYKlW5b9TeAzHCPHpf1MGGSivu2ZjEQb5xJvuI/edit?usp=sharing

**Comment by kartikderasari** [comment]
Hello @rominirani - I presented this session at Google IO Extended last year, happy to share the content incase it suits the criteria.

Thanks! :)

**Comment by rominirani** [comment]
Thank you
