### ISSUE TITLE
Kickstarting your Google Cloud Certification Journey

### ISSUE THREAD

**Issue by kartikderasari** [rominirani/googlecloud-indiacommunity-presentations#13]
- Date: November - December
- Event: Google Cloud Certification Journey program
- City: Online
- Your Name: Kartik Derasari
- Your talk topic: Kickstarting your Google Cloud Certification Journey 
- Presentation link: https://docs.google.com/presentation/d/1FiZC6sdu4tsrVkJAUQrJ0-bKGMeCvfRkI2JSu5acghk/edit?usp=sharing

**Comment by kartikderasari** [comment]
Hello @rominirani - I have been presenting this session for the Google Cloud Certification Journey program, happy to share the content incase it suits the criteria.

Thanks! :)

**Comment by rominirani** [comment]
Sure. It will be helpful to the community. While it may not necessarily be an event, it is part of the Certification program, which I am sure is useful to a wide range of community members.

**Comment by rominirani** [comment]
Thank you.
