### ISSUE TITLE
Cloud Community Days (CCD)

### ISSUE THREAD

**Issue by vaibhav-malpani** [rominirani/googlecloud-indiacommunity-presentations#14]
**CCD Mumbai**

- CCD Date: September 18, 2022
- CCD City: Mumbai
- Your Name: Vaibhav Malpani
- Your talk topic: Build ML Models using Vertex AI - Tables
- Deck link: https://docs.google.com/presentation/d/12b35b9ifPKv3sIQxXWvtnk3UVsoRAOQO/edit?usp=sharing&ouid=103691695454264324088&rtpof=true&sd=true

**Comment by rominirani** [comment]
Thanks.
