### ISSUE TITLE
Dev Fest Pune

### ISSUE THREAD

**Issue by AbiramiSukumaran** [rominirani/googlecloud-indiacommunity-presentations#15]
Date: December 11, 2022
City: Pune
Topic: Why now is the time to migrate your apps to managed databases
Deck link: https://docs.google.com/presentation/d/1JnNG0w47i6VkHwwU1sjNHcfJsaK2Z72PDmHykphEK4A/edit

**Comment by rominirani** [comment]
Thanks.
