### ISSUE TITLE
Add BLD201 talk from Google Cloud Next

### ISSUE THREAD

**Issue by ksprashu** [rominirani/googlecloud-indiacommunity-presentations#18]
Date : 12/10/2022
Event : Cloud Next 2022
City : Virtual / Online
Your Name : Prashanth Subrahmanyam
LinkedIn Profile URL : https://linkedin.com/in/ksprashu
Your talk topic : Building a serverless event-driven web app in under 10 mins
Brief Description (if you'd like) : In this talk, we’ll take a use case, break it down into composable pieces, and build an end-to-end application using the Google Cloud serverless portfolio of products.
Provide 3 links if you have:
Presentation link (This is mandatory) : https://assets.swoogo.com/uploads/2087852-633a59d429a69.pdf
Video link : https://www.youtube.com/watch?v=WUjBckEAb7Q

**Comment by rominirani** [comment]
Thanks.
