### ISSUE TITLE
Adding GCP content from Cloud Community Day- 2022

### ISSUE THREAD

**Issue by tushar-google** [rominirani/googlecloud-indiacommunity-presentations#2]
**CCD Gurgaon**
CCD Date: October 2, 2022
CCD City: Gurgaon
Your Name: Tushar Gupta
Your talk topic: Securing Modern Applications on Google Cloud Platform
Deck link:https://docs.google.com/presentation/d/152TnsUujYLGD1ffRbVZEWDfDxP9xfUVYgiMqKaIclwg/edit?usp=sharing

**Comment by rominirani** [comment]
Thanks.
