### ISSUE TITLE
Talks delivered at DevFests and Cloud Community Days 2022 

### ISSUE THREAD

**Issue by xprilion** [rominirani/googlecloud-indiacommunity-presentations#20]
### CCD Indore
- Date: September 10, 2022
- Event: Cloud Community Days
- City: Indore
- Your Name: Anubhav Singh
- Linkedin: https://linkedin.com/in/xprilion
- Your talk topic: Let’s Design a high availability ML heavy Cloud solution architecture
- Deck link: https://xpri.dev/high-availability-ml-system
- Repo link: https://github.com/xprilion/dummy-topology-loadtest
- Blog link: https://xprilion.com/high-availability-ml-deployments/

### CCD Mumbai
- Date: September 18, 2022
- Event: Cloud Community Days
- City: Mumbai
- Your Name: Anubhav Singh
- Linkedin: https://linkedin.com/in/xprilion
- Your talk topic: Cloud Costs Optimization: a story of $3000 to $150, at 10x the performance
- Deck link: https://xpri.dev/cloud-costs-story

### DevFest Mysuru
- Date: October 15, 2022
- Event: DevFest
- City: Mysuru
- Your Name: Anubhav Singh
- Linkedin: https://linkedin.com/in/xprilion
- Your talk topic: Finding insights in centuries-old photos -  A Google Cloud AI Story
- Deck link: https://xpri.dev/gcp-nytimes
- Video link: https://youtu.be/BWP8B63g_I0

### DevFest Gandhinagar
- Date: November 19, 2022
- Event: DevFest
- City: Gandhinagar
- Your Name: Anubhav Singh
- Linkedin: https://linkedin.com/in/xprilion
- Your talk topic: Cloud is all you need
- Deck link: https://xpri.dev/cloud-is-all-you-need

**Comment by rominirani** [comment]
Thanks.
