### ISSUE TITLE
Enterprise Database Migrations

### ISSUE THREAD

**Issue by pritamsahoo1982** [rominirani/googlecloud-indiacommunity-presentations#22]
Slide Link https://docs.google.com/presentation/d/1JVoXf8-iLbWKKe7X7805a1sbzBM-vOezcrtL2wibC6g/edit#slide=id.g125514d5365_0_10

Medium Blog Posts on DB Migrations
1. https://medium.com/google-cloud/fastrack-your-homogeneous-database-migration-for-postgresql-to-cloud-sql-postgresql-53a9259daca1
2. https://medium.com/google-cloud/comprehensive-approach-to-enterprise-database-migration-b242efc1ae98
3. https://medium.com/google-cloud/decision-tree-homogeneous-db-migration-to-cloud-sql-alloydb-with-gcp-database-migration-31e50edcc973
4. https://medium.com/google-cloud/heterogeneous-db-migrations-decision-tree-c27e22637666
5. https://medium.com/google-cloud/assessing-database-migration-complexities-with-migvisor-1ab600babe9d
6. https://medium.com/google-cloud/assessing-database-migration-complexities-with-migvisor-part-2-a35889bd3bda

Regards
Pritam

**Comment by rominirani** [comment]
Please submit details in the following format:

- Date
- Event (DevFest or Cloud Community Days or Cloud NEXT)
- City
- Your Name
- LinkedIn Profile URL
- Your talk topic
- Brief Description (if you'd like)
- Provide 3 links if you have:
    - Presentation link (This is mandatory)
    - Blog Post (Optional)
    - Repo Link (Optional)

**Comment by pritamsahoo1982** [comment]
Date - 18th Sept 2022
Event (DevFest or Cloud Community Days or Cloud NEXT) Devfest Bangalore 2022 & Hive@Next 2022
City - Bangalore
Your Name - Pritam Sahoo
LinkedIn Profile URL - https://www.linkedin.com/in/pritam-sahoo-77a438a/
Your talk topic - Enterprise Database Migrations
Brief Description (if you'd like) - 
Provide 3 links if you have:

Presentation link (This is mandatory) -  https://docs.google.com/presentation/d/1JVoXf8-iLbWKKe7X7805a1sbzBM-vOezcrtL2wibC6g/edit#slide=id.g125514d5365_0_10

Blog Post (Optional)

1. https://medium.com/google-cloud/fastrack-your-homogeneous-database-migration-for-postgresql-to-cloud-sql-postgresql-53a9259daca1
2. https://medium.com/google-cloud/comprehensive-approach-to-enterprise-database-migration-b242efc1ae98
3. https://medium.com/google-cloud/decision-tree-homogeneous-db-migration-to-cloud-sql-alloydb-with-gcp-database-migration-31e50edcc973
4. https://medium.com/google-cloud/heterogeneous-db-migrations-decision-tree-c27e22637666
5. https://medium.com/google-cloud/assessing-database-migration-complexities-with-migvisor-1ab600babe9d
6. https://medium.com/google-cloud/assessing-database-migration-complexities-with-migvisor-part-2-a35889bd3bda


Repo Link (Optional)

**Comment by rominirani** [comment]
Thanks.
