### ISSUE TITLE
Cloud Community Days (CCD)

### ISSUE THREAD

**Issue by PreritMunjal** [rominirani/googlecloud-indiacommunity-presentations#23]
### **Cloud Community Days New Delhi**

- Date: October 2nd, 2022
- City: New Delhi
- Name: Prerit Munjal
- LinkedIn: https://www.linkedin.com/in/prerit-munjal/
- Talk topic: Getting started with Cloud
- Description: Discussed about my jouney in cloud, certifications, skills needed,code vs cloud, and how to get the first job in cloud.
- Deck link: https://docs.google.com/presentation/d/1VSfOLdwOlX7Kq37CE3u6g3gPYiO_D6iHH51M745yvz0/edit?usp=sharing

**Comment by rominirani** [comment]
Thanks.
