### ISSUE TITLE
Adding GCP content from Cloud Community Days, Pune

### ISSUE THREAD

**Issue by bhis05** [rominirani/googlecloud-indiacommunity-presentations#24]
# CCD Pune

- Date: September 24, 2022
- City: Pune
- Your Name: Bhisham Malani
- Your talk topic: Google Architecture Diagramming Tool and New Features
- LinkedIn: www.linkedin.com/in/bhisham-malani/
- Deck link: https://github.com/bhis05/Cloud-Community-Days-Pune-2022/blob/main/CCD%202022%20Pune%20Presentation_Architecture%20Diagramming%20Tool.pdf

Apologies for late submission.. Great Initiative @rominirani - Really appreciate. 
Also, nice meeting you at Cloud Next Innovators hive event, Bangalore, Oct - 22.. Hope you are doing well.

**Comment by rominirani** [comment]
Thank you.
