### ISSUE TITLE
Add content from Cloud Next '22

### ISSUE THREAD

**Issue by roommen** [rominirani/googlecloud-indiacommunity-presentations#25]
**Cloud NEXT**

- Date: October 12, 2022
- City: Bangalore
- Your Name: Runcy Oommen
- Your talk topic: Security enhancements for popular GCP services
- Deck link: https://www.slideshare.net/RuncyOommen/security-enhancements-for-popular-gcp-services

**Comment by roommen** [comment]
Apologies for the late submission

**Comment by rominirani** [comment]
Thank you.
