### ISSUE TITLE
Content from CCD Ahmedabad

### ISSUE THREAD

**Issue by kaivalya97** [rominirani/googlecloud-indiacommunity-presentations#27]
Date: 24th September 2022
Event: Cloud Community Day
City: Ahmedabad
Name: Kaivalya Shah
Linkedin: https://linkedin.com/in/kaivalyashah
Talk topic: An Introduction to Serverless and Cloud Run 
Presentation: https://docs.google.com/presentation/d/1_FxtpbEbmR9HVwSgOWmXO7QXAYFadphe_UOZMHfG6lc/edit?usp=sharing

**Comment by rominirani** [comment]
Thank you.
