### ISSUE TITLE
CI/CD talk at DevFest Mumbai 2022

### ISSUE THREAD

**Issue by DSdatsme** [rominirani/googlecloud-indiacommunity-presentations#28]
Date: 5th Dec 2022
Event: DevFest
City: Mumbai
Name: Darshit Suratwala
LinkedIn: https://linkedin.com/in/dsdatsme
Topic: Infrastructure CI/CD using Open Source Tools
Description: Automate infrastructure provisioning using GitHub & Terraform

Presentation: https://docs.google.com/presentation/d/1dABxd4OGN97OPF3ITXKi4Q7QBtHNvbOA/edit?usp=sharing&ouid=112251394912774954952&rtpof=true&sd=true
Blog: https://medium.com/@dsdatsme/terraform-gitops-ci-cd-with-approval-notifications-6f0807299fc4
Repo: https://github.com/DSdatsme/gh-terraform

**Comment by rominirani** [comment]
Thank you.
