### ISSUE TITLE
Talks 2022 : Dharmesh Vaya

### ISSUE THREAD

**Issue by drvaya** [rominirani/googlecloud-indiacommunity-presentations#29]
**DevFest Chandigarh**

Date: December 17, 2022
Event: DevFest
City: Chandigarh, India
Your Name: Dharmesh Vaya
Linkedin: https://linkedin.com/in/dharmeshvaya
Your talk topic: Kubernetes Observability
Brief Description: Let us understand Observability !! You will find a range of tools on the CNCF ecosystem - How do we choose the right tool ? Let us understand some of the adapters and add-ons with Istio to collect a wide range of telemetry data. Some of the prominent ones being Prometheus to query metrics, then visualise using Grafana, visualise traces using Jaeger and finally visualise the service mesh using Kiali - everything using GKE.
Deck link: https://docs.google.com/presentation/d/1iqDcsfwBUaBOCtBPD6ipIMKa6JyiHnxb2fBzkG7Z_y4/edit?usp=sharing

**DevFest UlaanBaatar**

Date: December 08, 2022
Event: DevFest
City: UlaanBaatar, Mongolia
Your Name: Dharmesh Vaya
Linkedin: https://linkedin.com/in/dharmeshvaya
Your talk topic: Serverless on GCP
Brief Description: Serverless is leveraging the true potential of cloud - Performance, Availability and Scalability - all managed. Using GCP's suite of serverless products will help you design more robust and cheaper apps that are also easy to manage. Above all - it's applicable to all forms of applications like Web, Mobile Apps or even backend applications. This talk showcases with a demo a few products to design an end to end serverless app using Cloud Run, Cloud Functions and a few other tools to build a completely serverless architecture based application.
Deck link: https://docs.google.com/presentation/d/1V4_dqxFsKb5LttCtwYA3iZMXXDozcxOJ9aHUZbLbOvc/edit?usp=sharing
Video link: https://youtu.be/azMQul0MdTg?t=3757

**DevFest Tashkent**

Date: November 26, 2022
Event: DevFest
City: Tashkent, Uzbekistan
Your Name: Dharmesh Vaya
Linkedin: https://linkedin.com/in/dharmeshvaya
Your talk topic: CI/CD on GCP
Brief Description: How do you establish an end-to-end CI/CD with native services on GCP ?
Let us understand the CI/CD products and services within GCP. The talk covers a brief overview of Cloud Build, Artifact Registry and Cloud Deploy - covering deployment of Serverless applications as well as creating pipelines for GKE. Also will be covering how one can integrate external tools for code quality and container scanning. Overall a complete DevOps talk including security aspects.
Deck link: https://docs.google.com/presentation/d/18Rui-h4ctTZ4HYMcLqSmq5NEP2uWzxwm1-l3xnPp8S4/edit?usp=sharing

**Cloud Next Bengaluru**

Date: October 12, 2022
Event: Cloud Next
City: Bengaluru, India
Your Name: Dharmesh Vaya
Linkedin: https://linkedin.com/in/dharmeshvaya
Your talk topic: Time for some Chaos !!
Brief Description: How do you test your infrastructure esp. for resilience and reliability ? Create Chaos !
Let us understand Chaos Engineering - a branch of SRE that basically simulates any failures on your infra by injecting various faults. You basically proactively test your infra by breaking things with the ultimate goal of improving stability of the systems. The talk shall also showcase a demo using a popular Chaos Engineering tool like Gremlin and Litmus.
The demo covers the fundamental aspects of the Chaos Engineering Platform using Google Kubernetes Engine, understanding and designing Chaos Workflows, simulations for random pod deletion, network traffic and latency degradation, disk fill on ephemeral and persistent storage. Also, we shall cover the role of observability in Chaos Engg and some important metrics to find the resiliency score of your applications.
Deck link: https://docs.google.com/presentation/d/1dyjCvongAxJSkSbaY9dVOk2Jom0AbwN11ISJmqaVbmA/edit?usp=sharing&resourcekey=0-jMmRfMQSGyfmf4VrG1E6Wg
Video link: https://www.youtube.com/watch?v=lbxLc5OLZg4

**Cloud Community Days Jaipur**

Date: October 01, 2022
Event: Cloud Community Days
City: Jaipur, India
Your Name: Dharmesh Vaya
Linkedin: https://linkedin.com/in/dharmeshvaya
Your talk topic: Getting started with Deploying apps on GKE
Brief Description: This session aims to help users understand the working principles behind Google Kubernetes Engine including a hands-on lab. It introduces the fundamentals around micro-services, building container images and storing container images in Google Container Registry. Additionally, we shall also cover the K8S architecture, deploying a K8S cluster on GKE, deployment of Pods and overall how to manage the cluster and related K8S objects.
Deck link: https://docs.google.com/presentation/d/1zpLj-4T3oEG2YNtaHRYsab3UKe6crv_lrzpEHTKGWCQ/edit?usp=sharing

**Cloud Community Days Ahmedabad**

Date: September 24, 2022
Event: Cloud Community Days
City: Ahmedabad, India
Your Name: Dharmesh Vaya
Linkedin: https://linkedin.com/in/dharmeshvaya
Your talk topic: Getting started with Deploying apps on GKE
Brief Description: This session aims to help users understand the working principles behind Google Kubernetes Engine including a hands-on lab. It introduces the fundamentals around micro-services, building container images and storing container images in Google Container Registry. Additionally, we shall also cover the K8S architecture, deploying a K8S cluster on GKE, deployment of Pods and overall how to manage the cluster and related K8S objects.
Deck link: https://docs.google.com/presentation/d/1cGoVG94864zYZW28eoYhCoiesuVhj2mW2I3Ux8AfcKg/edit?usp=sharing

**Cloud Community Days Indore**

Date: September 10, 2022
Event: Cloud Community Days
City: Indore, India
Your Name: Dharmesh Vaya
Linkedin: https://linkedin.com/in/dharmeshvaya
Your talk topic: Multi-Tenancy in GKE 
Brief Description: Designing for Multi-tenancy on Kubernetes : Any SaaS platform when it scales - generally runs into this problem of a trade off - between infra and app. Should you isolate the app by hosting seperate instances or should you share the instances and have logical seperation. And top it up with Kubernetes - you add to the complexities. Let’s understand how to implement a multi-tenant solution on GKE.
Deck link: https://docs.google.com/presentation/d/1kDwykdkXBbit_m1egLYtngosOzif0N01KZwEMX6Gmvg/edit?usp=sharing
Video link: https://www.youtube.com/live/_aWn5xqd0eg?feature=share&t=8713

**Cloud Community Days Chennai**

Date: July 30, 2022
Event: Cloud Community Days
City: Chennai, India
Your Name: Dharmesh Vaya
Linkedin: https://linkedin.com/in/dharmeshvaya
Your talk topic: It was good until the bill arrived !!
Brief Description: Wasn’t the Cloud sold to you by the fact that it would reduce your IT expenditure. But now that you are adopting it across your organisation, are you seeing spurious spikes, unexplained charges and lot of additional costs into your invoices. You may have implemented DevOps now it’s time for FinOps. It is an operational framework and cultural shift that brings technology, finance, and business together to drive financial accountability and accelerate business value realization. Whatever stage of the cloud journey you’re at, FinOps practices will help you get the most value out of GCP (or any Cloud).
Deck link: https://docs.google.com/presentation/d/1K_DeD2oCVMmcGP2B83-eSI7jGt5Xm1DKfeISS56Nd2k/edit?usp=sharing

**Comment by drvaya** [comment]
My apologies for the extremely delayed submission.

**Comment by rominirani** [comment]
Thank you for submitting. No issues on the delay.
