### ISSUE TITLE
DevFest Jammu

### ISSUE THREAD

**Issue by saxeshik** [rominirani/googlecloud-indiacommunity-presentations#3]
Date : 19th Dec 2022
Event (DevFest or Cloud Community Days or Cloud NEXT) DevFest
City : Jammu
Your Name : Shikha Saxena
Your talk topic : Life in Google (Keynote session)
Brief Description (if you'd like) : The session was about life in Google, opportunities in Google for early career / startups, How Google Developer group can add value 
Provide 3 links if you have:
Presentation link (This is mandatory) https://docs.google.com/presentation/d/1dWXSMrIl4PHZUeJmEz4vReZvF5B91e95qwn4ps-2irM/edit#slide=id.g1bbdaaebf67_0_6948

**Comment by rominirani** [comment]
Thank you.
