### ISSUE TITLE
Build your career in Data Engineering using Google Cloud

### ISSUE THREAD

**Issue by iNiravKothari** [rominirani/googlecloud-indiacommunity-presentations#30]
Date - 7th May 2023
Event - Cloud Community Days
City - Kolkata
Your Name - Nirav Kothari
LinkedIn Profile URL - www.linkedin.com/in/iniravkothari
Your talk topic - Build your career in Data Engineering using Google Cloud
Brief Description (if you'd like) - The talk briefed audience about how does entire development landscape look like and evolves when organization grows from small scale to large scale, What are various development roles contributing to building that. And followed by the responsibilities of the data engineer. The talk also talked about what kind of projects consulting organization handles in the data engineering space.
Provide 3 links if you have:
Presentation link (This is mandatory) - https://docs.google.com/presentation/d/1UG12YtfnMTscDuqcEi0jDiRgqfEolUBgz3lf7cKk6-Y/edit?usp=sharing
Blog Post (Optional)
Repo Link (Optional)
If you would like to submit a PR, please submit it in the appropriate PRESENTATIONS.md file in the specific year folder (e.g. 2022, 2023)

**Comment by rominirani** [comment]
Thank you Nirav.
