### ISSUE TITLE
Adding Presentations from Cloud Community Days

### ISSUE THREAD

**Issue by rastogiji** [rominirani/googlecloud-indiacommunity-presentations#31]
## CCD Bhubaneswar 2023
- CCD Date: 19th march, 2023
- CCD City: Bhubaneswar 
- Your Name: Animesh Rastogi
- Your Talk Topic: Progressive Delivery on Kubernetes with Argo and Istio
- Deck Link: https://docs.google.com/presentation/d/1MqM57-6-_yoXuV0jctKWk6J7ro91QdVAPHIlWjFmGbA/edit?usp=sharing

## CCD Bangalore 2023
- CCD Date: 20th May, 2023
- CCD City: Bangalore
- Your Name: Animesh Rastogi
- Your Talk Topic: Scaling Observability in Production
- Deck Link: https://docs.google.com/presentation/d/12RqZYF88aLHpL-LYH2LlqTgn6GgLqyK0TficycbX3VA/edit?usp=sharing

**Comment by rominirani** [comment]
Thanks.
