### ISSUE TITLE
CCD Kolkata

### ISSUE THREAD

**Issue by vaibhav-malpani** [rominirani/googlecloud-indiacommunity-presentations#32]
**Date:** 7 May
**Event:** Cloud Community Days
**City**: Kolkata
**Your Name**: Vaibhav Malpani
**LinkedIn Profile URL**: https://www.linkedin.com/in/ivaibhavmalpani/
**Your talk topic**: Where should I run my stuff?
**Brief Description**: The talk will help you decide which models are the best fit for your systems as well as how the models map to Google Cloud services — whether Compute Engine, Container Engine, Cloud Run, App Engine, and/or Cloud Functions.
**Deck link**: https://drive.google.com/file/d/1-fcs7aLDxpd0gLP85RC6TkMsb_mV3B67/view?usp=sharing

**Comment by rominirani** [comment]
Thanks.
