### ISSUE TITLE
CCD Delhi -2023

### ISSUE THREAD

**Issue by tushar-google** [rominirani/googlecloud-indiacommunity-presentations#34]
Date: May 20, 2023
Event City: Delhi
Event Name: Google Cloud Community Day 2023 - Delhi
Your Name: Tushar Gupta
LinkedIn Profile Link: www.linkedin.com/in/tusharguptag
Your talk topic: Secure your Software Supply Chain
Session Description: This session will cover the current threat scenario in Software Delivery and how by adopting GCP, we can protect our business assets being developed leveraging Google Cloud' Software Delivery Shield
Deck link: https://docs.google.com/presentation/d/1kaKPE4KY9qwtS_DqE6UcFejyCKddO_SkuyBVjC0JPgI/edit?usp=sharing

**Comment by tushar-google** [comment]
@rominirani Please check and revert in case of any further information required

**Comment by rominirani** [comment]
Thank you. Added it to the list of presentations.
