### ISSUE TITLE
CCD Pune

### ISSUE THREAD

**Issue by saurabhmi2212** [rominirani/googlecloud-indiacommunity-presentations#35]
Date :  27/05/2023
Event  :- CCD ,Pune
City :  Pune
Your Name :  Saurabh Mishra
LinkedIn Profile URL :- https://www.linkedin.com/in/connectsaurabhmishra/
Your talk topic :- Google Cloud simplifies Zero Trust Approach
Brief Description (if you'd like) : Details explanation and understanding about zero trust approach and how Google Cloud services simplifies and enhances securities with tenets risk awareness, least privileged access, and continuous access verification. How does Google define the concept of Zero Trust, and how does Beyond Corp Enterprise fit into this solution. We will also discuss about What are the big challenges your customers are facing today in terms of authenticating and securing users, and how can these Zero Trust principles help mitigate against them?

Presentation link :-https://docs.google.com/presentation/d/1yBU8_QJUYoh-qfCk18PPKdjwS0ThNoTT/edit#slide=id.p1

**Comment by rominirani** [comment]
Thanks
