### ISSUE TITLE
Adding GDG Cloud Community Days Bangalore 2022 and 2023

### ISSUE THREAD

**Issue by saradindusengupta** [rominirani/googlecloud-indiacommunity-presentations#39]
# Cloud Community Days (CCD)
## CCD Bangalore, 2022
Date: August 07, 2022
City: Bangalore
Your Name: Saradindu Sengupta
Topic: Managing data quality in ML with ML
Description: Brief overview of understanding when the data for ML inferencing has gone bad and ways to detect it.
Presentation: https://docs.google.com/presentation/d/1JLIQV9XUUXrO1CGGuWqC27qegSTN3imR/edit?usp=sharing&ouid=107197486862317920392&rtpof=true&sd=true
## CCD Bangalore, 2023
Date: May 20, 2023
City: Bangalore
Your Name: Saradindu Sengupta
Topic: Interpretable ML in production
Description: Validating an ML model with train-test accuracy metrics offers an initial understanding of viability but generating consistent inferencing with contextual business goals requires understanding how the deployed model works in different nature and how they will behave in case of soft data drift.
Presentation: https://docs.google.com/presentation/d/1kLBGkRBG5eopMvQ_zgU0v9HOZcFdY3DVLt7R5bKQVl0/edit?usp=sharing

**Comment by rominirani** [comment]
Thank you for your submissions. I have added the respective presentations to 2022 and 2023.
