### ISSUE TITLE
DevFest Mumbai 2022

### ISSUE THREAD

**Issue by pamitk** [rominirani/googlecloud-indiacommunity-presentations#4]
* Date: Monday, 5 Dec 2022
* Event (DevFest or Cloud Community Days or Cloud NEXT) : Devfest Mumbai 2022
* City: Mumbai
* Your Name: Amitkumar Pandey
* Your talk topic : Application security techniques and best practices on Google Cloud Platform
* Provide 3 links if you have:
    * Repo link : https://github.com/pamitk/DevFestMumbai/blob/main/Application%20Security%20Techniques%20-%20DevFest%20Mumbai%20Dec%202022.pdf

**Comment by rominirani** [comment]
Thank you.
