### ISSUE TITLE
Adding GCCD 2023 talks

### ISSUE THREAD

**Issue by xprilion** [rominirani/googlecloud-indiacommunity-presentations#40]
### GCCD Bhopal
- Date: April 16, 2023
- Event: Google Cloud Community Days
- City: Bhopal
- Your Name: Anubhav Singh
- Linkedin: https://linkedin.com/in/xprilion
- Your talk topic: Job Scheduling on Google Cloud Platform
- Description: A session exploring the various tools available on GCP for job scheduling. We discuss how to implement barebones cron jobs and how to eventually transition to Cloud Scheduler and other job scheduling services on GCP.
- Deck link: https://xpri.dev/gcp-job-scheduling
- Blog link: https://xprilion.com/job-scheduling-on-google-cloud-platform/

### GCCD Chennai
- Date: May 13, 2023
- Event: Google Cloud Community Days
- City: Chennai
- Your Name: Anubhav Singh
- Linkedin: https://linkedin.com/in/xprilion
- Your talk topic: Cloud Run services as backends to Load Balancers
- Description: In this talk, we discuss using Google Cloud Run as a backend for load balancing in the Google Cloud Platform. We cover the benefits of Cloud Run, such as automatic scaling, stateless and concurrent processing, integration with Google Cloud services, and cost-effectiveness.
- Deck link: https://xpri.dev/cloud-run-load-balancer

**Comment by rominirani** [comment]
Thanks and merged.
