### ISSUE TITLE
DevFest Belgaum 2022

### ISSUE THREAD

**Issue by pilotudesh** [rominirani/googlecloud-indiacommunity-presentations#5]
- Date - 10 December 2022
- Event - DevFest Belgaum 2022
- Udesh Udayakumar
- Anthos Service Mesh & Kubernetes
- Brief Description - An introduction to Anthos Service Mesh and Kubernetes
- Presentation link - 
- https://docs.google.com/presentation/d/1U2oKBd15DyetorpCwRLIPjQ1-9JyyOe98XflKnaFO4Y/edit?usp=sharing

**Comment by rominirani** [comment]
Thank you.
