### ISSUE TITLE
Presentations by Yogesh Haribhau Kulkarni for Google related events in 2023

### ISSUE THREAD

**Issue by yogeshhk** [rominirani/googlecloud-indiacommunity-presentations#56]
23 Dec 2023 : Dev Fest Pune - Generative AI FAQ Bot -  https://github.com/yogeshhk/TeachingDataScience/blob/89ebcc7ff42597dcbc2dccec0e5b3ed98f2f8e4b/Presentations/DF23%20-%20Generative%20AI%20FAQ%20Bot%20-%20Yogesh%20Kulkarni.pdf
28 Oct 2023 : Dev Fest Coimbatore - Generative AI FAQ Bot - --"--

27 May 2023 : CCD Pune - Introduction to Graph Data Science - https://github.com/yogeshhk/TeachingDataScience/blob/89ebcc7ff42597dcbc2dccec0e5b3ed98f2f8e4b/Presentations/GCCD%20Pune%2023_Graph%20Data%20Science_Presentation.pdf

20 May 2023: I/O Ext Pune - Prompt Engineering - https://github.com/yogeshhk/TeachingDataScience/blob/89ebcc7ff42597dcbc2dccec0e5b3ed98f2f8e4b/Presentations/GoogleIOExt_Pune_PromptEngg_Presentation.pdf

16 Apr 2023: GDSC Wow Pune - Zero to ChatGPT - https://github.com/yogeshhk/TeachingDataScience/blob/89ebcc7ff42597dcbc2dccec0e5b3ed98f2f8e4b/Presentations/GDSCWoWPune_Seminar_ChatGPT_FromZero_Presentation.pdf

Developer profile: https://developers.google.com/profile/u/yogeshkulkarni

**Comment by rominirani** [comment]
Thank you.
