### ISSUE TITLE
Adding GCP content from Cloud Community Days- The Westin, Gurgaon, Delhi

### ISSUE THREAD

**Issue by aparna2071** [rominirani/googlecloud-indiacommunity-presentations#6]
- Date: 2 October, 2022
- Event (DevFest or Cloud Community Days or Cloud NEXT) : Cloud Community Days
- City : Gurgaon
- Your Name : Aparna Soneja
- Your talk topic : Open source & Hacktoberfest
- Brief Description (if you'd like)
- Provide 3 links if you have: 
Presentation link (This is mandatory) : https://docs.google.com/presentation/d/1heTOG-SUR2YyivYbNk5YbTx9SvppLWClTp2YvgQA2hs/edit?usp=sharing
Blog Post (Optional)
Repo Link (Optional)

**Comment by rominirani** [comment]
Thanks.
