### ISSUE TITLE
Adding GCP content from DevFest- Noida

### ISSUE THREAD

**Issue by aparna2071** [rominirani/googlecloud-indiacommunity-presentations#7]
- Date : 11 December, 2022
- Event (DevFest or Cloud Community Days or Cloud NEXT) : DevFest
- City : Noida
- Your Name : Aparna Soneja
- Your talk topic : Open discussion on the topic- Open source
- Brief Description (if you'd like)
- Provide 3 links if you have:
Presentation link (This is mandatory) : This was an open discussion in which I answered the queries of audience, therefore it doesn't have any presentation.
Blog Post (Optional)
Repo Link (Optional)

**Comment by rominirani** [comment]
Aparna -- Thanks for the submission. Since this is without a presentation, I will skip adding this entry. I have added your other presentation to the list of talks.
