### ISSUE TITLE
Data Governance on Google Cloud

### ISSUE THREAD

**Issue by iNiravKothari** [rominirani/googlecloud-indiacommunity-presentations#9]
Cloud NEXT
Date: October 13, 2022
City: Bangalore
Your Name: Nirav Kothari
Your talk topic: Data Governance on Google Cloud
Deck link: https://docs.google.com/presentation/d/18l7w5TUN8cm_ZYe8NsQo6-8v5nBMVwotOnHKqNa4ftY/edit?usp=sharing&resourcekey=0-vffr_7DlV-M0yeHj79PAcw

DevFest UlaanBaatar 2022
Date: December 8, 2022
City: UlaanBaatar, Mongolia
Your Name: Nirav Kothari
Your talk topic: All about databases - Selection to Operationalization
Deck link: https://docs.google.com/presentation/d/15ve8N0d21xDCSQP6svfpb9aFYskDV-u9/edit?usp=sharing&ouid=113134168822208668234&rtpof=true&sd=true

**Comment by rominirani** [comment]
Thanks.
